### ISSUE TITLE
ACT French - The player using the ACT does not appear in

### ISSUE THREAD

**Issue by Faster01** [Inkraja/Advanced-Combat-Tracker#14]
Hello,
First of all thank you for your work :)

I use ACT on the French client, the problem that I will explain happens to those I know who the client in French.
I use the SecretParser 1.0.7.2 from ACT website and software 3.3.1 release 255

The one who launches the ACT does not appear in the fight only in heal but not in DPS

I have not seen a post related to this issue so I post it here.
I joined an act and a longcombat after a fight against two vampires in trans3

If i can help tel me :)
Faster

![capture_1](https://user-images.githubusercontent.com/30570697/28753706-6d28d7ec-7538-11e7-9b59-f6643d36d976.JPG)
![faster-2017-07-30-15-03-08](https://user-images.githubusercontent.com/30570697/28753713-8c18cb9e-7538-11e7-9ba1-28179f3448e7.png)
[CombatLog-2017-07-30_1428.txt](https://github.com/Inkraja/Advanced-Combat-Tracker/files/1185689/CombatLog-2017-07-30_1428.txt)

**Comment by Vikijaka** [comment]
Take a look at Issue #11 also take a look at the secretparser @ https://github.com/Inkraja/Advanced-Combat-Tracker/tree/develop-swl

**Comment by Faster01** [comment]
Thanks you,
I have test with the secretparser @ DevBranch but same issue.

**Comment by Vikijaka** [comment]
Sorry that i have to ask this, but are u sure u are using the right secretparser and changed it to the right in ACT?

Also please show me/us your "Secret Parsing/Generel" Screen - i don't think that this is a "secretparser.cs" related error/bug.

If i switch to french client, every thing is getting parsed well

**Comment by Faster01** [comment]
This is the screen of my Secret Parsing/General

![capture_1](https://user-images.githubusercontent.com/30570697/28754259-5d46822a-7542-11e7-81bb-ecdfc331ca68.JPG)

**Comment by Vikijaka** [comment]
Disable "Auto check [...] for Updates" after that go to Plugins Tab and delete your actual secretparser.cs Plugin. Download the dev secretparser.cs and add this. restart ACT+Game

also i have imported your combatlog from above, its not the same as your screenshot, but everything is getting parse

**Comment by Faster01** [comment]
I have make it like you tell me and same issue ^^

I have bad configure other thing maybe
![capture_1](https://user-images.githubusercontent.com/30570697/28754399-d4a8576a-7544-11e7-9286-397067148eb6.JPG)
![capture_2](https://user-images.githubusercontent.com/30570697/28754403-dc1fe1d4-7544-11e7-8280-20f4fd997249.JPG)

**Comment by JustBoorish** [comment]
Please uncheck the "Enable TSWACT Addon features" option.  Also Make sure your character name is set correctly in the Options->Data Correction->Miscellaneous section.  I don't expect these to fix the issue, I just want to ensure you are using the same settings as I am.  Your logfile parses correctly for me.

**Comment by Vikijaka** [comment]
![a1](https://user-images.githubusercontent.com/29962702/28754542-851475c8-7547-11e7-9a5e-a0e706c9287c.JPG)
![a2](https://user-images.githubusercontent.com/29962702/28754543-885a96a4-7547-11e7-8f08-a61acaf1314c.JPG)
![a3](https://user-images.githubusercontent.com/29962702/28754544-8ae35a50-7547-11e7-8c61-9b33b41946b6.JPG)

Some example of Solo Polaris - everythign is fine! :)

**Comment by Faster01** [comment]
I have test with this config and it's the same :s 

We are here for testing ^^
![capture_1](https://user-images.githubusercontent.com/30570697/28754615-e7ee61a8-7548-11e7-82e0-6ca52683f46d.JPG)
![capture_3](https://user-images.githubusercontent.com/30570697/28754613-e7ead2fe-7548-11e7-9750-3c13cb6f59df.JPG)
![capture_4](https://user-images.githubusercontent.com/30570697/28754616-e80adba8-7548-11e7-9cdb-d152f9a29594.JPG)
![capture_2](https://user-images.githubusercontent.com/30570697/28754614-e7ec532c-7548-11e7-86e3-252cfc7d1d4f.JPG)

**Comment by Faster01** [comment]
I also just test with "show self damage" and "show by player" cheked and with a "/logcombat off" and "/logcombat on"

**Comment by JustBoorish** [comment]
The reason ACT is showing NaN for you is the it thinks the encounter lasted less than one second.  That is what the [00:00] means beside the encounter name on the left hand panel.  Can you import your combat log into ACT to see if you still get the issue with imported logs.  You can do this by clicking on the Import/Export tab and pressing the Select File button.  Then press the Use Above button on the window that pops up.  Once this is complete you will see the encounters in the Main tab under the Import Zone.

**Comment by JustBoorish** [comment]
Ok, I've managed to reproduce your issue.  You are not using the development version of the parser.  If I use the release version I get your problem.  If I use the development version it works fine.  Please use this link to get the development version of the parser and retest: https://raw.githubusercontent.com/Inkraja/Advanced-Combat-Tracker/develop-swl/SecretParser.cs

**Comment by Faster01** [comment]
Now it's work fine. 
It was the bad version of parser.
Thanks You and sorry for that
