### ISSUE TITLE
AutoUpdate from Github ignored

### ISSUE THREAD

**Issue by Inkraja** [Inkraja/Advanced-Combat-Tracker#17]
It seem so, since Boorish put 1.0.7.2 update on the official ACT, the latest github version are not recognized correctly.

Can someone with more skills check the issue?

**Comment by JustBoorish** [comment]
Looks like a security change on the github site.  It is failing with an SSL error.  I'll put a fix on the branch.

**Comment by JustBoorish** [comment]
Can someone please verify the auto update fix works for them?  Code is on develop-swl branch.

**Comment by Inkraja** [comment]
is it does! 😍 
main Issue will be to spread it, since the updater didnt inform people for a new version...

**Comment by JustBoorish** [comment]
I'll ask the ACT author to make this the new default on his site.  That should spread the fix.
