### ISSUE TITLE
Keziah's Mason Ring tracks as separate player

### ISSUE THREAD

**Issue by Philip-Trettner** [Inkraja/Advanced-Combat-Tracker#6]
See https://gyazo.com/3aa72bc67838357f7635e2d87ce9e072
The ring is https://gyazo.com/96cdf195d66065830aa1671cd64fbe96
It's a flappy nm drop

**Comment by JochenSchwander** [comment]
Can you post the log entries that caused this please?

**Comment by Philip-Trettner** [comment]
I guess it works similar to the Protector's Wrath but I'll check once I get home.

**Comment by Philip-Trettner** [comment]
`[18:55:47] Katarina1's Keziah Mason's Ring hits (Normal) Abominated Soldier for 46 physical damage. (Normal)`

**Comment by JochenSchwander** [comment]
should be fixed in Version 1.0.6.9001 pre 1.0.7.0
