### ISSUE TITLE
Personal Pain

### ISSUE THREAD

**Issue by Inkraja** [Inkraja/Advanced-Combat-Tracker#8]
Mir ist aufgefallen, dass wenn Attacker = Target die gleiche Person ist, dass "No Damage" angezeigt wird. Im Combat Log steht es aber korrekt mit Zahlen.

Im gleichen Screenshot sieht man auch DijkeMark, er hat ebenfalls No Damage
https://gyazo.com/495664096b1ddc2d587dc07fa88b5f98

**Comment by JochenSchwander** [comment]
sollte unter _self_ oder _self_Duoe aufgelistet sein, je nach den ausgewählten optionen. Is so damit z.B. blood offering nicht mit in die gewirkten dps zählt

**Comment by AnnaDamm** [comment]
Nunja, eigentlich ist es Eidolon und nicht Duoe, der das Mass Hysteria auslöst. Er zaubert es nur AUF duoe, und alle drum herum bekommen Schaden.

**Comment by JochenSchwander** [comment]
Dann sag das mal Funcom das die bitte ins logfile schreiben sollen das der schaden von eido kommt und ned dem spieler dens trifft ;)
