### ISSUE TITLE
Update for SWL

### ISSUE THREAD

**Issue by Inkraja** [Inkraja/Advanced-Combat-Tracker#9]
what i have seen so far:
 - penetration and blocked hits are removed - not a issue 
 - evaded hit and evaded attacks are still available and correct counted as "miss" 
- Line 61 are a new format

Example: HR normal + questing in SC, Names from other Players are replaced with Player2 and 3
[CombatLog-2017-06-05_2112.txt](https://github.com/Inkraja/Advanced-Combat-Tracker/files/1065745/CombatLog-2017-06-05_2112.txt)

**Comment by JochenSchwander** [comment]
I'm not even sure if I will play SWL or invest time in a parser for it. Since the updater for the TSW parser uses this repository it would make sense to fork it into a new one for a SWL parser to avoid changes affecting TSW.

**Comment by Inkraja** [comment]
I generate a own branch, but i dont think its recommend that we split both, as long tsw and swl combat logs are really similar.

Its more add the new casts and the new format.

If they really add stuff that needs a own parser we can split it at this point.

**Comment by JustBoorish** [comment]
I think that splitting the parsers makes sense.  We are already seeing differences in the French and German log formats.  It will only get worse over time as TSW stays dormant and SWL evolves.

**Comment by Inkraja** [comment]
Well... iam waiting till funcom announced that the tsw servers will be shut down till end of the year (or next). If u log in in the game you will notice that maybe 2-3 players are currently online.

And please, commit first at the swl branch till all changes are tested and than merge it to the master branch.

In the case we need to split it, its much easier than that
